import Header from "@/components/Header";
import './globals.css';
import {ApolloWrapper} from "@/lib/apollo-wrapper";
import PollPage from "@/components/Test";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
    <body>
    <ApolloWrapper>
      <Header/>
      <PollPage></PollPage>
      {children}
    </ApolloWrapper>
    </body>
    </html>
  )
}
